export enum KafkaTopic {
  EVENT_BUS = 'event-bus',
  DEAD_LETTER_QUEUE = 'dead-letter-queue',
}

export enum KafkaEvent {
  AGENT_CREATED = 'AGENT_CREATED',
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_CLASSIFIED = 'TICKET_CLASSIFIED',
  TENANT_DOC_UPLOADED = 'TENANT_DOC_UPLOADED',
  RETRIEVE_CONTEXT = 'RETRIEVE_CONTEXT',
}
