export enum KafkaTopic {
  EVENT_BUS = 'event-bus',
  DEAD_LETTER_QUEUE = 'dead-letter-queue',
}

export enum KafkaEvent {
  AGENT_CREATED = 'AGENT_CREATED',
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_CLASSIFIED = 'TICKET_CLASSIFIED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TENANT_DOC_UPLOADED = 'TENANT_DOC_UPLOADED',
  TENANT_DOC_PARSED = 'TENANT_DOC_PARSED',
  TENANT_DOC_CHUNKED = 'TENANT_DOC_CHUNKED',
  TENANT_DOC_EMBEDDINGS_GENERATED = 'TENANT_DOC_EMBEDDINGS_GENERATED',
}
