export enum AuditLogAction {
  TENANT_CREATE = 'TENANT_CREATE',
  ADMIN_CREATE = 'ADMIN_CREATE',
  AGENT_CREATE = 'AGENT_CREATE',
  CUSTOMER_CREATE = 'CUSTOMER_CREATE',
  SYSTEM_CREATE = 'SYSTEM_CREATE',
  LOGIN_ATTEMPT = 'LOGIN_ATTEMPT',
  UPLOAD_DOC = 'UPLOAD_DOC',
  CREATE_TICKET = 'CREATE_TICKET',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
}

export enum AuditLogEntityType {
  TENANT = 'TENANT',
  USER = 'USER',
  TENANT_DOC = 'TENANT_DOC',
  TICKET = 'TICKET',
}
