export enum AuditLogAction {
  TENANT_CREATE = 'TENANT_CREATE',
  ADMIN_CREATE = 'ADMIN_CREATE',
  AGENT_CREATE = 'AGENT_CREATE',
  CUSTOMER_CREATE = 'CUSTOMER_CREATE',
  SYSTEM_USER_CREATE = 'SYSTEM_USER_CREATE',
  LOGIN_ATTEMPT = 'LOGIN_ATTEMPT',
  UPLOAD_DOC = 'UPLOAD_DOC',
  DOC_KNOWLEDGE_INGEST = 'DOC_KNOWLEDGE_INGEST',
  CREATE_TICKET = 'CREATE_TICKET',
  CLASSIFY_TICKET = 'CLASSIFY_TICKET',
  ASSIGN_TICKET = 'ASSIGN_TICKET',
  GENERATE_AI_RESPONSE = 'GENERATE_AI_RESPONSE',
  REVIEW_AI_RESPONSE = 'REVIEW_AI_RESPONSE',
}

export enum AuditLogEntityType {
  TENANT = 'TENANT',
  USER = 'USER',
  TENANT_DOC = 'TENANT_DOC',
  TICKET = 'TICKET',
  MESSAGE = 'MESSAGE',
}
