export enum EnvConfigEnum {
  NODE_ENV = 'NODE_ENV',
  APP_PORT = 'APP_PORT',
  JWT_SECRET = 'JWT_SECRET',
  DATABASE_URL = 'DATABASE_URL',
  USER_DEFAULT_PASSWORD = 'USER_DEFAULT_PASSWORD',
  AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_S3_BUCKET = 'AWS_S3_BUCKET',
  KAFKA_CLIENT_ID = 'KAFKA_CLIENT_ID',
  KAFKA_GROUP_ID = 'KAFKA_GROUP_ID',
  KAFKA_BROKER = 'KAFKA_BROKER',
  OLLAMA_TEXT_GENERATION_URL = 'OLLAMA_TEXT_GENERATION_URL',
  OLLAMA_EMBEDDING_GENERATION_URL = 'OLLAMA_EMBEDDING_GENERATION_URL',
  OLLAMA_MODEL = 'OLLAMA_MODEL',
}

export enum NodeEnvironmentEnum {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}
